services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: nectar-api

    ports:
      - "8010:8010"

    env_file:
      - .env

    volumes:
      - .:/app
      - /app/node_modules

    command: npm run dev

    stdin_open: true
    tty: true

    restart: unless-stopped
