name: 🚀 Build & Deploy Nectar Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🚀 Deploy Application
        run: |
          set -e

          APP_DIR=/home/robiul/vps/apps/nectar-api

          cd $APP_DIR

          echo "📌 Saving current commit..."
          PREVIOUS_COMMIT=$(git rev-parse HEAD)

          echo "⬇ Fetch latest code..."
          git fetch origin main
          git reset --hard origin/main

          echo "📦 Installing packages..."
          npm ci

          echo "🔍 TypeScript checking..."
          npm run build

          echo "♻ Reload PM2..."
          pm2 reload nectar-api --update-env

          echo "✅ Deployment Success"